import os
import sys
import platform

ROOT=os.environ['ROOT'];
BIN_DIR=os.environ['BIN_DIR'];
GTEST_ROOT=os.environ['GTEST_ROOT'];

env=DefaultEnvironment().Clone();

env['LIBS'] = ['fish_keyboard'] + env['LIBS']
INCLUDE_PATH = [
  ROOT, 
  GTEST_ROOT,
  os.path.join(ROOT, 'src'),
  os.path.join(GTEST_ROOT, 'src'),
  os.path.join(GTEST_ROOT, 'include'),
  os.path.join(GTEST_ROOT, 'make')
] 

env['CPPPATH'] = env['CPPPATH'] + INCLUDE_PATH

SOURCES = [
 os.path.join(GTEST_ROOT, 'src/gtest-all.cc'),
] + Glob('*.cc') + Glob('*.c')

env.Program(os.path.join(BIN_DIR, 'runTest'), SOURCES);


