import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];

LIBS = ['cjson'] + env['LIBS']
env.Program(os.path.join(BIN_DIR, 'key_code_map_gen'), [ Glob('key_code_map_gen/*.cc') + Glob('key_code_map_gen/*.c')], LIBS=LIBS)


