import os
import sys
import platform

OS_NAME = platform.system();
env=DefaultEnvironment().Clone()
LIB_DIR=os.environ['LIB_DIR'];

SOURCES= Glob("base/*.c") + \
  Glob("keyboard/*.c") + \
  Glob("led_animators/*.c") + \
  Glob('*.c')

env.Library(os.path.join(LIB_DIR, 'fish_keyboard'), SOURCES)
